"use client";

import { useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { PendingButton } from "@/components/ui/pending-button";
import { saveDefenceBrief } from "@/lib/actions/briefs-admin";

type Section = { question: string; answer: string; points: string[] };
type SourceLink = { sourceId: string; citationNote: string; displayOrder: number };
type RecordLink = { recordType: "organization" | "capability" | "demand_requirement"; recordId: string; relationshipLabel: string; displayOrder: number };
export type BriefDraft = { id: string; slug: string; title: string; primaryQuestion: string; summaryAnswer: string; dek: string; sections: Section[]; derivedRead: string; seoTitle: string; metaDescription: string; authorName: string; publicationStatus: "draft" | "published" | "archived"; sourceLinks: SourceLink[]; recordLinks: RecordLink[] };
export type BriefSourceOption = { id: string; title: string; publisher: string };
export type BriefRecordOption = { id: string; type: RecordLink["recordType"]; name: string };

const field = "rounded-xl border border-[var(--atlas-border)] bg-white px-3 py-2.5 text-sm text-[var(--atlas-ink)] outline-none focus:border-[var(--atlas-primary)]";
const area = `${field} min-h-24 leading-6`;
const blank: BriefDraft = { id: "", slug: "new-defence-brief", title: "", primaryQuestion: "", summaryAnswer: "", dek: "", sections: [{ question: "", answer: "", points: [] }], derivedRead: "", seoTitle: "", metaDescription: "", authorName: "Andrew Davies", publicationStatus: "draft", sourceLinks: [], recordLinks: [] };
const slugify = (value: string) => value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 100) || "new-defence-brief";

export function DefenceBriefEditor({ initial, sources, records }: { initial?: BriefDraft; sources: BriefSourceOption[]; records: BriefRecordOption[] }) {
  const [draft, setDraft] = useState(initial ?? blank);
  const update = <K extends keyof BriefDraft>(key: K, value: BriefDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const payload = { ...draft, slug: draft.id ? draft.slug : slugify(draft.title), sourceLinks: undefined, recordLinks: undefined, id: undefined };
  return <form action={saveDefenceBrief} className="grid gap-5">
    <input type="hidden" name="pageId" value={draft.id} /><input type="hidden" name="payload" value={JSON.stringify(payload)} /><input type="hidden" name="sourceLinks" value={JSON.stringify(draft.sourceLinks)} /><input type="hidden" name="recordLinks" value={JSON.stringify(draft.recordLinks)} />
    <div className="grid gap-4 md:grid-cols-2"><Field label="Public page title"><input className={field} value={draft.title} onChange={(e) => update("title", e.target.value)} minLength={8} required /></Field><Field label="Main question" help="Write this the way a person would ask it in search or Ask True North."><input className={field} value={draft.primaryQuestion} onChange={(e) => update("primaryQuestion", e.target.value)} minLength={12} required /></Field></div>
    <Field label="Short answer" help="Answer the main question directly in one useful paragraph."><textarea className={area} value={draft.summaryAnswer} onChange={(e) => update("summaryAnswer", e.target.value)} minLength={40} required /></Field>
    <Field label="Page introduction"><textarea className={area} value={draft.dek} onChange={(e) => update("dek", e.target.value)} minLength={40} required /></Field>
    <div className="space-y-4">{draft.sections.map((section, index) => <section key={index} className="rounded-2xl border border-[var(--atlas-border)] bg-[var(--atlas-surface-muted)] p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-extrabold">Key question {index + 1}</h3>{draft.sections.length > 1 ? <button type="button" onClick={() => update("sections", draft.sections.filter((_, i) => i !== index))} className="text-[var(--atlas-muted)]"><Trash2 className="size-4" /></button> : null}</div><div className="mt-3 grid gap-3"><input className={field} placeholder="Question" value={section.question} onChange={(e) => update("sections", draft.sections.map((item, i) => i === index ? { ...item, question: e.target.value } : item))} required /><textarea className={area} placeholder="Direct answer" value={section.answer} onChange={(e) => update("sections", draft.sections.map((item, i) => i === index ? { ...item, answer: e.target.value } : item))} required /><textarea className={field} rows={3} placeholder="Supporting points, one per line" value={section.points.join("\n")} onChange={(e) => update("sections", draft.sections.map((item, i) => i === index ? { ...item, points: e.target.value.split("\n").map((point) => point.trim()).filter(Boolean) } : item))} /></div></section>)}</div>
    <button type="button" onClick={() => update("sections", [...draft.sections, { question: "", answer: "", points: [] }])} className="atlas-secondary-button w-fit px-4 py-2 text-xs"><Plus className="mr-2 size-4" />Add key question</button>
    <Field label="What this may mean" help="Optional interpretation. The public page labels this as a Derived Read."><textarea className={area} value={draft.derivedRead} onChange={(e) => update("derivedRead", e.target.value)} /></Field>
    <div className="grid gap-4 md:grid-cols-2"><Field label="Search title"><input className={field} value={draft.seoTitle} onChange={(e) => update("seoTitle", e.target.value)} required /></Field><Field label="Search description"><textarea className={field} rows={3} value={draft.metaDescription} onChange={(e) => update("metaDescription", e.target.value)} minLength={40} required /></Field></div>
    <Field label="Public sources" help="A published brief must link at least one approved public source."><select className={field} value="" onChange={(e) => { const source = sources.find((item) => item.id === e.target.value); if (source && !draft.sourceLinks.some((item) => item.sourceId === source.id)) update("sourceLinks", [...draft.sourceLinks, { sourceId: source.id, citationNote: `Public evidence from ${source.publisher}.`, displayOrder: draft.sourceLinks.length + 1 }]); }}><option value="">Add a source…</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.publisher} · {source.title}</option>)}</select><div className="grid gap-2">{draft.sourceLinks.map((link, index) => { const source = sources.find((item) => item.id === link.sourceId); return <div key={link.sourceId} className="grid gap-2 rounded-xl border border-[var(--atlas-border)] p-3 md:grid-cols-[1fr_2fr_auto]"><span className="text-xs font-semibold">{source?.title ?? link.sourceId}</span><input className={field} value={link.citationNote} onChange={(e) => update("sourceLinks", draft.sourceLinks.map((item, i) => i === index ? { ...item, citationNote: e.target.value } : item))} /><button type="button" onClick={() => update("sourceLinks", draft.sourceLinks.filter((_, i) => i !== index))}><Trash2 className="size-4" /></button></div>; })}</div></Field>
    <Field label="Related records" help="Give readers a useful next step into a public need, company, or technology."><select className={field} value="" onChange={(e) => { const record = records.find((item) => `${item.type}:${item.id}` === e.target.value); if (record && !draft.recordLinks.some((item) => item.recordType === record.type && item.recordId === record.id)) update("recordLinks", [...draft.recordLinks, { recordType: record.type, recordId: record.id, relationshipLabel: "Explore the related record", displayOrder: draft.recordLinks.length + 1 }]); }}><option value="">Add a related record…</option>{records.map((record) => <option key={`${record.type}:${record.id}`} value={`${record.type}:${record.id}`}>{record.type.replace("_", " ")} · {record.name}</option>)}</select><div className="grid gap-2">{draft.recordLinks.map((link, index) => { const record = records.find((item) => item.id === link.recordId && item.type === link.recordType); return <div key={`${link.recordType}:${link.recordId}`} className="grid gap-2 rounded-xl border border-[var(--atlas-border)] p-3 md:grid-cols-[1fr_2fr_auto]"><span className="text-xs font-semibold">{record?.name ?? link.recordId}</span><input className={field} value={link.relationshipLabel} onChange={(e) => update("recordLinks", draft.recordLinks.map((item, i) => i === index ? { ...item, relationshipLabel: e.target.value } : item))} /><button type="button" onClick={() => update("recordLinks", draft.recordLinks.filter((_, i) => i !== index))}><Trash2 className="size-4" /></button></div>; })}</div></Field>
    <div className="grid gap-4 md:grid-cols-2"><Field label="Author"><input className={field} value={draft.authorName} onChange={(e) => update("authorName", e.target.value)} /></Field><Field label="Status"><select className={field} value={draft.publicationStatus} onChange={(e) => update("publicationStatus", e.target.value as BriefDraft["publicationStatus"])}><option value="draft">Private draft</option><option value="published">Reviewed and public</option><option value="archived">Archived</option></select></Field></div>
    <PendingButton type="submit" pendingLabel="Saving brief…" className="atlas-primary-button w-fit px-5 py-3 text-sm"><Save className="mr-2 size-4" />{draft.publicationStatus === "published" ? "Publish brief" : "Save brief"}</PendingButton>
  </form>;
}

function Field({ label, help, children }: { label: string; help?: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-xs font-bold text-[var(--atlas-ink-soft)]"><span>{label}</span>{children}{help ? <span className="text-[11px] font-normal leading-5 text-[var(--atlas-muted)]">{help}</span> : null}</label>; }
