import Link from "next/link";
import { BarChart3, Bot, Database, Eye, MailCheck, ShieldCheck } from "lucide-react";
import { PublicCard, PublicPageShell } from "@/components/atlas/public-page-shell";
import { AnalyticsPreferencesButton } from "@/components/atlas/public-beta-insights";
import { socialMetadata } from "@/lib/seo/social";

export const metadata = {
  title: "Privacy",
  description: "How True North Map handles accounts, contributions, connections, messages, feedback, analytics, and retention.",
  alternates: { canonical: "/privacy" },
  ...socialMetadata({ title: "True North Map Privacy", description: "How True North Map handles accounts, contributions, connections, messages, analytics, and retention.", path: "/privacy", eyebrow: "Privacy and participation" })
};

export default function PrivacyPage() {
  return (
    <PublicPageShell eyebrow="Public-beta governance" title="Privacy and participation" description="True North Map collects only the information needed to operate private workflows, improve discovery, and respond to voluntary contact." backHref="/" backLabel="Home">
      <div className="grid gap-5 lg:grid-cols-2">
        <PublicCard title="Sign-in and private work" eyebrow="User-controlled actions"><ShieldCheck className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">You can use Google or a passwordless email link. Google provides a verified email and basic profile information; the service never receives your Google or email password. Working Lists, contributions, and connection requests are private to you and the authorized administrator.</p></PublicCard>
        <PublicCard title="North Signal and contact" eyebrow="Affirmative consent"><MailCheck className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">North Signal subscription stores your email, the exact consent language and version, signup placement, landing page, and delivery status. The free weekly briefing is the default. When Defence Signal alerts are enabled, they are an optional, separately versioned preference that is never added without a fresh affirmative choice. MailerLite delivers the selected email streams using an authenticated True North Map sender. The preference system supports weekly only, alerts only, both, or clearing both to unsubscribe globally; alert controls remain hidden until the provider capability and preference experience are approved. Consent and withdrawal history remains private. Contact messages store only the details you enter and a one-way request fingerprint used for rate limiting.</p></PublicCard>
        <PublicCard title="Product learning" eyebrow="Meaningful actions only"><Eye className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">Vercel provides aggregate traffic and performance measures. Private product telemetry records meaningful discovery actions and the North Signal funnel, including a landing view, sample click, qualified impression, prompt open, form start, submit attempt, successful consent write, error, or dismissal. These events use bounded route, placement, device, UTM source/medium/content and campaign context only. Email addresses and search questions are never attached to newsletter behaviour events. Raw IP addresses are not stored in the product database, and analytics are not used to build advertising profiles.</p></PublicCard>
        <PublicCard title="Search and Ask True North" eyebrow="Two distinct paths"><Bot className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">The map&apos;s direct record search matches the published catalogue without using OpenAI and is not retained as an Ask True North question. When you deliberately open and use Ask True North, your question and a compact copy of the published catalogue are sent to OpenAI to produce a structured assessment. Responses are not stored by OpenAI through this integration. True North Map keeps the Ask question privately for up to 90 days to understand search gaps and records limited operational measures such as latency, token use, result count, and outcome. Do not enter classified, confidential, proprietary, or personal information.</p></PublicCard>
        <PublicCard title="Retention and review" eyebrow="Limited and private"><Database className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">Raw search text expires after 90 days and detailed workflow events after 30 days. Aggregate daily product-usage counts, without visitor identifiers, search text or individual campaign details, are retained privately for up to 400 days to evaluate improvements. Feedback, contact, consent, submissions, and connection requests remain private for review, follow-up, governance, and audit until no longer needed. Published records use approved public evidence only.</p></PublicCard>
      </div>
      <PublicCard title="Optional analytics" eyebrow="A simple choice" className="mt-5">
        <div className="rounded-2xl border border-[var(--atlas-border)] bg-[var(--atlas-surface-muted)] p-4"><BarChart3 className="size-5 text-[var(--atlas-primary)]" /><h3 className="mt-3 text-sm font-bold text-[var(--atlas-ink)]">Product analytics</h3><p className="mt-2 text-xs leading-6 text-[var(--atlas-muted)]">If you allow it, Google Analytics records sanitized public-page visits and broad interaction patterns. URL search parameters, private account and administration routes, Google Signals, user-provided form content, and advertising personalization are excluded.</p></div>
        <p className="mt-4 text-xs leading-6 text-[var(--atlas-muted)]">Optional analytics are disabled until you accept them. The first notice offers a simple accept or decline choice without blocking the site. You can change that choice here at any time. Vercel Analytics, Google Analytics, MailerLite, Supabase, Resend, OpenAI, MapTiler, and OpenStreetMap process limited information only for the functions described here and under their applicable privacy terms. Map providers receive ordinary browser requests only when a public map is loaded.</p>
      </PublicCard>
      <PublicCard title="Your choices" eyebrow="Access, correction, and removal" className="mt-5"><p className="text-sm leading-6 text-[var(--atlas-muted)]">You can browse without an account, manage or delete your account and owner-bound private data from <Link href="/account" className="font-semibold text-[var(--atlas-primary)] underline">Your account</Link>, dismiss the North Signal prompt for 30 days, submit a correction, and withdraw through the functional unsubscribe link. A delivery-preference experience will be exposed only after it is approved and verified; clearing both weekly and alert delivery is then a global unsubscribe, while a new preference still requires an affirmative local consent action. You can also <AnalyticsPreferencesButton className="font-semibold text-[var(--atlas-primary)] underline" /> at any time. Published records and anonymized audit history are not removed with a member account. Use the <Link href="/contact" className="font-semibold text-[var(--atlas-primary)] underline">contact form</Link> or email <a href="mailto:privacy@truenorthmap.ca" className="font-semibold text-[var(--atlas-primary)] underline">privacy@truenorthmap.ca</a> for another access, correction, or privacy request. Last updated September 5, 2026.</p></PublicCard>
    </PublicPageShell>
  );
}
