import Link from "next/link";
import { BarChart3, Bot, Database, Eye, MailCheck, MousePointer2, ShieldCheck } from "lucide-react";
import { PublicCard, PublicPageShell } from "@/components/atlas/public-page-shell";
import { AnalyticsPreferencesButton } from "@/components/atlas/public-beta-insights";

export const metadata = {
  title: "Privacy",
  description: "How True North Map handles accounts, contributions, connections, messages, feedback, analytics, and retention.",
  alternates: { canonical: "/privacy" }
};

export default function PrivacyPage() {
  return (
    <PublicPageShell eyebrow="Public-beta governance" title="Privacy and participation" description="True North Map collects only the information needed to operate private workflows, improve discovery, and respond to voluntary contact.">
      <div className="grid gap-5 lg:grid-cols-2">
        <PublicCard title="Sign-in and private work" eyebrow="User-controlled actions"><ShieldCheck className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">You can use Google or a passwordless email link. Google provides a verified email and basic profile information; the service never receives your Google or email password. Working Lists, contributions, and connection requests are private to you and the authorized administrator.</p></PublicCard>
        <PublicCard title="Updates and contact" eyebrow="Affirmative consent"><MailCheck className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">Update signup stores your email, the consent language and version, source, and status. Contact messages store the details you enter and a one-way request fingerprint used for rate limiting. Updates are delivered through an authenticated True North Map sender and include a compliant unsubscribe path.</p></PublicCard>
        <PublicCard title="Product learning" eyebrow="Meaningful actions only"><Eye className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">Vercel provides aggregate traffic and performance measures. Private product telemetry records meaningful discovery actions such as searches, filters, zero results, profiles, sources, exports, saves, contributions, connections, subscriptions, and feedback. Raw IP addresses are not stored in the product database, and analytics are not used to build advertising profiles.</p></PublicCard>
        <PublicCard title="Ask True North" eyebrow="Public records only"><Bot className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">When you use Ask True North, your question and a compact copy of the published catalogue are sent to OpenAI to produce a structured assessment. Responses are not stored by OpenAI through this integration. True North Map keeps the question privately for up to 90 days to understand search gaps and records limited operational measures such as latency, token use, result count, and outcome. Do not enter classified, confidential, proprietary, or personal information.</p></PublicCard>
        <PublicCard title="Retention and review" eyebrow="Limited and private"><Database className="mb-3 size-5 text-[var(--atlas-primary)]" /><p className="text-sm leading-6 text-[var(--atlas-muted)]">Raw search text expires after 90 days and detailed workflow events after 30 days. Feedback, contact, consent, submissions, and connection requests remain private for review, follow-up, governance, and audit until no longer needed. Published records use approved public evidence only.</p></PublicCard>
      </div>
      <PublicCard title="Optional analytics" eyebrow="You choose what loads" className="mt-5">
        <div className="grid gap-4 md:grid-cols-2">
          <div className="rounded-2xl border border-[var(--atlas-border)] bg-[var(--atlas-surface-muted)] p-4"><BarChart3 className="size-5 text-[var(--atlas-primary)]" /><h3 className="mt-3 text-sm font-bold text-[var(--atlas-ink)]">Product analytics</h3><p className="mt-2 text-xs leading-6 text-[var(--atlas-muted)]">If you allow it, Google Analytics records sanitized public-page visits and broad interaction patterns. URL search parameters, private account and administration routes, Google Signals, user-provided form content, and advertising personalization are excluded.</p></div>
          <div className="rounded-2xl border border-[var(--atlas-border)] bg-[var(--atlas-surface-muted)] p-4"><MousePointer2 className="size-5 text-[var(--atlas-primary)]" /><h3 className="mt-3 text-sm font-bold text-[var(--atlas-ink)]">Experience diagnostics</h3><p className="mt-2 text-xs leading-6 text-[var(--atlas-muted)]">If available and you allow it, Microsoft Clarity provides heatmaps and session replays of public pages so layout and usability problems can be understood. Private routes are excluded. Input fields are masked by default, and True North Map explicitly masks search, signup, feedback, contact, connection, and contribution forms.</p></div>
        </div>
        <p className="mt-4 text-xs leading-6 text-[var(--atlas-muted)]">Both choices are optional and disabled until you allow them. You can allow one, both, or neither, and change your selection at any time. Vercel Analytics, Google Analytics, Microsoft Clarity, MailerLite, Supabase, Resend, OpenAI, and MapTiler process limited information only for the functions described here and under their applicable privacy terms.</p>
      </PublicCard>
      <PublicCard title="Your choices" eyebrow="Access, correction, and removal" className="mt-5"><p className="text-sm leading-6 text-[var(--atlas-muted)]">You can browse without an account, manage or delete your account and owner-bound private data from <Link href="/account" className="font-semibold text-[var(--atlas-primary)] underline">Your account</Link>, dismiss the update prompt for 30 days, submit a correction, and unsubscribe from future updates during deletion. You can also <AnalyticsPreferencesButton className="font-semibold text-[var(--atlas-primary)] underline" /> at any time. Published records and anonymized audit history are not removed with a member account. Use the <Link href="/contact" className="font-semibold text-[var(--atlas-primary)] underline">contact form</Link> or email <a href="mailto:privacy@truenorthmap.ca" className="font-semibold text-[var(--atlas-primary)] underline">privacy@truenorthmap.ca</a> for another access, correction, or privacy request. Last updated July 25, 2026.</p></PublicCard>
    </PublicPageShell>
  );
}
